-- AlterTable
ALTER TABLE "inventory_item" ADD COLUMN     "safe_min_qty" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "warning_max_qty" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "warning_min_qty" DOUBLE PRECISION NOT NULL DEFAULT 20;
