
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
export const prismaVersion: PrismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  user: 'user',
  service_option: 'service_option',
  customer: 'customer',
  queue_ticket: 'queue_ticket',
  inventory_item: 'inventory_item',
  inventory_adjustment: 'inventory_adjustment',
  order_inventory_usage: 'order_inventory_usage'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "service_option" | "customer" | "queue_ticket" | "inventory_item" | "inventory_adjustment" | "order_inventory_usage"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    user: {
      payload: Prisma.$userPayload<ExtArgs>
      fields: Prisma.userFieldRefs
      operations: {
        findUnique: {
          args: Prisma.userFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.userFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        findFirst: {
          args: Prisma.userFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.userFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        findMany: {
          args: Prisma.userFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>[]
        }
        create: {
          args: Prisma.userCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        createMany: {
          args: Prisma.userCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.userCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>[]
        }
        delete: {
          args: Prisma.userDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        update: {
          args: Prisma.userUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        deleteMany: {
          args: Prisma.userDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.userUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.userUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>[]
        }
        upsert: {
          args: Prisma.userUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$userPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.userGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.userCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    service_option: {
      payload: Prisma.$service_optionPayload<ExtArgs>
      fields: Prisma.service_optionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.service_optionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.service_optionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        findFirst: {
          args: Prisma.service_optionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.service_optionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        findMany: {
          args: Prisma.service_optionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>[]
        }
        create: {
          args: Prisma.service_optionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        createMany: {
          args: Prisma.service_optionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.service_optionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>[]
        }
        delete: {
          args: Prisma.service_optionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        update: {
          args: Prisma.service_optionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        deleteMany: {
          args: Prisma.service_optionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.service_optionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.service_optionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>[]
        }
        upsert: {
          args: Prisma.service_optionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$service_optionPayload>
        }
        aggregate: {
          args: Prisma.Service_optionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateService_option>
        }
        groupBy: {
          args: Prisma.service_optionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Service_optionGroupByOutputType>[]
        }
        count: {
          args: Prisma.service_optionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Service_optionCountAggregateOutputType> | number
        }
      }
    }
    customer: {
      payload: Prisma.$customerPayload<ExtArgs>
      fields: Prisma.customerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.customerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.customerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        findFirst: {
          args: Prisma.customerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.customerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        findMany: {
          args: Prisma.customerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>[]
        }
        create: {
          args: Prisma.customerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        createMany: {
          args: Prisma.customerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.customerCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>[]
        }
        delete: {
          args: Prisma.customerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        update: {
          args: Prisma.customerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        deleteMany: {
          args: Prisma.customerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.customerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.customerUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>[]
        }
        upsert: {
          args: Prisma.customerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$customerPayload>
        }
        aggregate: {
          args: Prisma.CustomerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCustomer>
        }
        groupBy: {
          args: Prisma.customerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CustomerGroupByOutputType>[]
        }
        count: {
          args: Prisma.customerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CustomerCountAggregateOutputType> | number
        }
      }
    }
    queue_ticket: {
      payload: Prisma.$queue_ticketPayload<ExtArgs>
      fields: Prisma.queue_ticketFieldRefs
      operations: {
        findUnique: {
          args: Prisma.queue_ticketFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.queue_ticketFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        findFirst: {
          args: Prisma.queue_ticketFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.queue_ticketFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        findMany: {
          args: Prisma.queue_ticketFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>[]
        }
        create: {
          args: Prisma.queue_ticketCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        createMany: {
          args: Prisma.queue_ticketCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.queue_ticketCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>[]
        }
        delete: {
          args: Prisma.queue_ticketDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        update: {
          args: Prisma.queue_ticketUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        deleteMany: {
          args: Prisma.queue_ticketDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.queue_ticketUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.queue_ticketUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>[]
        }
        upsert: {
          args: Prisma.queue_ticketUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$queue_ticketPayload>
        }
        aggregate: {
          args: Prisma.Queue_ticketAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQueue_ticket>
        }
        groupBy: {
          args: Prisma.queue_ticketGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_ticketGroupByOutputType>[]
        }
        count: {
          args: Prisma.queue_ticketCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Queue_ticketCountAggregateOutputType> | number
        }
      }
    }
    inventory_item: {
      payload: Prisma.$inventory_itemPayload<ExtArgs>
      fields: Prisma.inventory_itemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.inventory_itemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.inventory_itemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        findFirst: {
          args: Prisma.inventory_itemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.inventory_itemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        findMany: {
          args: Prisma.inventory_itemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>[]
        }
        create: {
          args: Prisma.inventory_itemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        createMany: {
          args: Prisma.inventory_itemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.inventory_itemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>[]
        }
        delete: {
          args: Prisma.inventory_itemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        update: {
          args: Prisma.inventory_itemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        deleteMany: {
          args: Prisma.inventory_itemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.inventory_itemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.inventory_itemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>[]
        }
        upsert: {
          args: Prisma.inventory_itemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_itemPayload>
        }
        aggregate: {
          args: Prisma.Inventory_itemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInventory_item>
        }
        groupBy: {
          args: Prisma.inventory_itemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Inventory_itemGroupByOutputType>[]
        }
        count: {
          args: Prisma.inventory_itemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Inventory_itemCountAggregateOutputType> | number
        }
      }
    }
    inventory_adjustment: {
      payload: Prisma.$inventory_adjustmentPayload<ExtArgs>
      fields: Prisma.inventory_adjustmentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.inventory_adjustmentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.inventory_adjustmentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        findFirst: {
          args: Prisma.inventory_adjustmentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.inventory_adjustmentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        findMany: {
          args: Prisma.inventory_adjustmentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>[]
        }
        create: {
          args: Prisma.inventory_adjustmentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        createMany: {
          args: Prisma.inventory_adjustmentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.inventory_adjustmentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>[]
        }
        delete: {
          args: Prisma.inventory_adjustmentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        update: {
          args: Prisma.inventory_adjustmentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        deleteMany: {
          args: Prisma.inventory_adjustmentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.inventory_adjustmentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.inventory_adjustmentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>[]
        }
        upsert: {
          args: Prisma.inventory_adjustmentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$inventory_adjustmentPayload>
        }
        aggregate: {
          args: Prisma.Inventory_adjustmentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInventory_adjustment>
        }
        groupBy: {
          args: Prisma.inventory_adjustmentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Inventory_adjustmentGroupByOutputType>[]
        }
        count: {
          args: Prisma.inventory_adjustmentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Inventory_adjustmentCountAggregateOutputType> | number
        }
      }
    }
    order_inventory_usage: {
      payload: Prisma.$order_inventory_usagePayload<ExtArgs>
      fields: Prisma.order_inventory_usageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.order_inventory_usageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.order_inventory_usageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        findFirst: {
          args: Prisma.order_inventory_usageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.order_inventory_usageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        findMany: {
          args: Prisma.order_inventory_usageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>[]
        }
        create: {
          args: Prisma.order_inventory_usageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        createMany: {
          args: Prisma.order_inventory_usageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.order_inventory_usageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>[]
        }
        delete: {
          args: Prisma.order_inventory_usageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        update: {
          args: Prisma.order_inventory_usageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        deleteMany: {
          args: Prisma.order_inventory_usageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.order_inventory_usageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.order_inventory_usageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>[]
        }
        upsert: {
          args: Prisma.order_inventory_usageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_inventory_usagePayload>
        }
        aggregate: {
          args: Prisma.Order_inventory_usageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrder_inventory_usage>
        }
        groupBy: {
          args: Prisma.order_inventory_usageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Order_inventory_usageGroupByOutputType>[]
        }
        count: {
          args: Prisma.order_inventory_usageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Order_inventory_usageCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  user_id: 'user_id',
  full_name: 'full_name',
  username: 'username',
  password_hash: 'password_hash',
  role: 'role',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  created_by_id: 'created_by_id'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const Service_optionScalarFieldEnum = {
  service_option_id: 'service_option_id',
  name: 'name',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Service_optionScalarFieldEnum = (typeof Service_optionScalarFieldEnum)[keyof typeof Service_optionScalarFieldEnum]


export const CustomerScalarFieldEnum = {
  customer_id: 'customer_id',
  name: 'name',
  phone_number: 'phone_number',
  created_at: 'created_at'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const Queue_ticketScalarFieldEnum = {
  ticket_id: 'ticket_id',
  ticket_date: 'ticket_date',
  queue_number: 'queue_number',
  customer_id: 'customer_id',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  called_at: 'called_at',
  finished_at: 'finished_at',
  skipped_at: 'skipped_at',
  canceled_at: 'canceled_at',
  machine_done_at: 'machine_done_at',
  machine_notified_by: 'machine_notified_by',
  machine_notified_at: 'machine_notified_at',
  handled_by: 'handled_by',
  service_option_id: 'service_option_id',
  custom_service_name: 'custom_service_name',
  order_qty: 'order_qty',
  order_note: 'order_note',
  pickup_method: 'pickup_method',
  machine_worker_name: 'machine_worker_name',
  usage_submitted_at: 'usage_submitted_at'
} as const

export type Queue_ticketScalarFieldEnum = (typeof Queue_ticketScalarFieldEnum)[keyof typeof Queue_ticketScalarFieldEnum]


export const Inventory_itemScalarFieldEnum = {
  inventory_item_id: 'inventory_item_id',
  name: 'name',
  unit: 'unit',
  stock_initial: 'stock_initial',
  stock_out: 'stock_out',
  stock_available: 'stock_available',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type Inventory_itemScalarFieldEnum = (typeof Inventory_itemScalarFieldEnum)[keyof typeof Inventory_itemScalarFieldEnum]


export const Inventory_adjustmentScalarFieldEnum = {
  inventory_adjustment_id: 'inventory_adjustment_id',
  inventory_item_id: 'inventory_item_id',
  qty_adjustment: 'qty_adjustment',
  reason: 'reason',
  input_by: 'input_by',
  created_at: 'created_at'
} as const

export type Inventory_adjustmentScalarFieldEnum = (typeof Inventory_adjustmentScalarFieldEnum)[keyof typeof Inventory_adjustmentScalarFieldEnum]


export const Order_inventory_usageScalarFieldEnum = {
  order_inventory_usage_id: 'order_inventory_usage_id',
  ticket_id: 'ticket_id',
  inventory_item_id: 'inventory_item_id',
  qty_good: 'qty_good',
  qty_waste: 'qty_waste',
  qty_total_used: 'qty_total_used',
  input_by: 'input_by',
  created_at: 'created_at'
} as const

export type Order_inventory_usageScalarFieldEnum = (typeof Order_inventory_usageScalarFieldEnum)[keyof typeof Order_inventory_usageScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'UserRole'
 */
export type EnumUserRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserRole'>
    


/**
 * Reference to a field of type 'UserRole[]'
 */
export type ListEnumUserRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserRole[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'TicketStatus'
 */
export type EnumTicketStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TicketStatus'>
    


/**
 * Reference to a field of type 'TicketStatus[]'
 */
export type ListEnumTicketStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TicketStatus[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    


/**
 * Reference to a field of type 'PickupMethod'
 */
export type EnumPickupMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PickupMethod'>
    


/**
 * Reference to a field of type 'PickupMethod[]'
 */
export type ListEnumPickupMethodFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PickupMethod[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.userOmit
  service_option?: Prisma.service_optionOmit
  customer?: Prisma.customerOmit
  queue_ticket?: Prisma.queue_ticketOmit
  inventory_item?: Prisma.inventory_itemOmit
  inventory_adjustment?: Prisma.inventory_adjustmentOmit
  order_inventory_usage?: Prisma.order_inventory_usageOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

