
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  OWNER: 'OWNER',
  COUNTER_SERVICE: 'COUNTER_SERVICE',
  MACHINE: 'MACHINE'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const PickupMethod = {
  DITUNGGU: 'DITUNGGU',
  DITINGGAL: 'DITINGGAL'
} as const

export type PickupMethod = (typeof PickupMethod)[keyof typeof PickupMethod]


export const TicketStatus = {
  WAITING: 'WAITING',
  SERVING: 'SERVING',
  DONE: 'DONE',
  SKIPPED: 'SKIPPED',
  CANCEL: 'CANCEL'
} as const

export type TicketStatus = (typeof TicketStatus)[keyof typeof TicketStatus]
